In [1]:
#imoporting all required liberies 
import pandas as pd
import numpy as np

In [2]:
#loading the dataset
df = pd.read_csv("C:/Users/Admin/Downloads/archive/KaggleV2-May-2016.csv")

In [3]:
#view the data head 
df.head()

,PatientId,AppointmentID,Gender,ScheduledDay,AppointmentDay,Age,Neighbourhood,Scholarship,Hipertension,Diabetes,Alcoholism,Handcap,SMS_received,No-show
0,2.987250e+13,5642903,F,2016-04-29T18:38:08Z,2016-04-29T00:00:00Z,62,JARDIM DA PENHA,0,1,0,0,0,0,No
1,5.589978e+14,5642503,M,2016-04-29T16:08:27Z,2016-04-29T00:00:00Z,56,JARDIM DA PENHA,0,0,0,0,0,0,No
2,4.262962e+12,5642549,F,2016-04-29T16:19:04Z,2016-04-29T00:00:00Z,62,MATA DA PRAIA,0,0,0,0,0,0,No
3,8.679512e+11,5642828,F,2016-04-29T17:29:31Z,2016-04-29T00:00:00Z,8,PONTAL DE CAMBURI,0,0,0,0,0,0,No
4,8.841186e+12,5642494,F,2016-04-29T16:07:23Z,2016-04-29T00:00:00Z,56,JARDIM DA PENHA,0,1,1,0,0,0,No

In [4]:
#to view numeric stat of the dataset
df.describe()

,PatientId,AppointmentID,Age,Scholarship,Hipertension,Diabetes,Alcoholism,Handcap,SMS_received
count,1.105270e+05,1.105270e+05,110527.000000,110527.000000,110527.000000,110527.000000,110527.000000,110527.000000,110527.000000
mean,1.474963e+14,5.675305e+06,37.088874,0.098266,0.197246,0.071865,0.030400,0.022248,0.321026
std,2.560949e+14,7.129575e+04,23.110205,0.297675,0.397921,0.258265,0.171686,0.161543,0.466873
min,3.921784e+04,5.030230e+06,-1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,4.172614e+12,5.640286e+06,18.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,3.173184e+13,5.680573e+06,37.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,9.439172e+13,5.725524e+06,55.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
max,9.999816e+14,5.790484e+06,115.000000,1.000000,1.000000,1.000000,1.000000,4.000000,1.000000

In [5]:
# Row and column count
print(f'Rows: {df.shape[0]}')
print(f'Columns: {df.shape[1]}')

Rows: 110527
Columns: 14

In [6]:
# Column names and data types
print(df.dtypes)

PatientId         float64
AppointmentID       int64
Gender             object
ScheduledDay       object
AppointmentDay     object
Age                 int64
Neighbourhood      object
Scholarship         int64
Hipertension        int64
Diabetes            int64
Alcoholism          int64
Handcap             int64
SMS_received        int64
No-show            object
dtype: object

In [7]:
# Null counts per column
print(df.isnull().sum())

PatientId         0
AppointmentID     0
Gender            0
ScheduledDay      0
AppointmentDay    0
Age               0
Neighbourhood     0
Scholarship       0
Hipertension      0
Diabetes          0
Alcoholism        0
Handcap           0
SMS_received      0
No-show           0
dtype: int64

In [8]:
print(df.duplicated().sum())

0

In [9]:
# Renaming the columns to snake_case
df.columns = df.columns.str.lower().str.replace('-', '_')
df.rename(columns={
    'patientid': 'patient_id',
    'appointmentid': 'appointment_id',
    'scheduledday': 'scheduled_date',
    'appointmentday': 'appointment_date',
    'neighbourhood': 'clinic',
    'no_show': 'no_show'
}, inplace=True)

In [10]:
df.head()

,patient_id,appointment_id,gender,scheduled_date,appointment_date,age,clinic,scholarship,hipertension,diabetes,alcoholism,handcap,sms_received,no_show
0,2.987250e+13,5642903,F,2016-04-29T18:38:08Z,2016-04-29T00:00:00Z,62,JARDIM DA PENHA,0,1,0,0,0,0,No
1,5.589978e+14,5642503,M,2016-04-29T16:08:27Z,2016-04-29T00:00:00Z,56,JARDIM DA PENHA,0,0,0,0,0,0,No
2,4.262962e+12,5642549,F,2016-04-29T16:19:04Z,2016-04-29T00:00:00Z,62,MATA DA PRAIA,0,0,0,0,0,0,No
3,8.679512e+11,5642828,F,2016-04-29T17:29:31Z,2016-04-29T00:00:00Z,8,PONTAL DE CAMBURI,0,0,0,0,0,0,No
4,8.841186e+12,5642494,F,2016-04-29T16:07:23Z,2016-04-29T00:00:00Z,56,JARDIM DA PENHA,0,1,1,0,0,0,No

In [11]:
# Convert date columns
df['scheduled_date'] = pd.to_datetime(df['scheduled_date']).dt.date
df['appointment_date'] = pd.to_datetime(df['appointment_date']).dt.date

In [12]:
df['age'].describe()

count    110527.000000
mean         37.088874
std          23.110205
min          -1.000000
25%          18.000000
50%          37.000000
75%          55.000000
max         115.000000
Name: age, dtype: float64

In [13]:
# Filter invalid ages (0-100 range)
df = df[(df['age'] >= 0) & (df['age'] <= 100)]

In [14]:
# Handle missing clinic names
df['clinic'] = df['clinic'].fillna('Unknown')

In [15]:
# Calculate wait_days
df['wait_days'] = (pd.to_datetime(df['appointment_date']) - 
                   pd.to_datetime(df['scheduled_date'])).dt.days

In [16]:
# Convert no_show to binary (1 = Yes/No-show, 0 = No/Showed up)
df['no_show'] = df['no_show'].map({'Yes': 1, 'No': 0})

In [17]:
#to check for the no_show rate
df['no_show'].value_counts(normalize=True) * 100

no_show
0    79.807997
1    20.192003
Name: proportion, dtype: float64

In [18]:
#to check the number of patients that received an sms
df['sms_received'].value_counts()

#this shows the no-show rate for patients who got sms & those who did not
df.groupby('sms_received')['no_show'].mean() * 100

sms_received
0    16.700872
1    27.575322
Name: no_show, dtype: float64

In [19]:
#to show the wait_days by no_show status
df.groupby('no_show')['wait_days'].mean()

no_show
0     8.754963
1    15.831645
Name: wait_days, dtype: float64

In [20]:
# Save as cleaned data
df.to_csv('appointments_cleaned.csv', index=False)
print(f"Cleaned dataset: {len(df)} rows")

Cleaned dataset: 110519 rows

In [21]:
df.head()

,patient_id,appointment_id,gender,scheduled_date,appointment_date,age,clinic,scholarship,hipertension,diabetes,alcoholism,handcap,sms_received,no_show,wait_days
0,2.987250e+13,5642903,F,2016-04-29,2016-04-29,62,JARDIM DA PENHA,0,1,0,0,0,0,0,0
1,5.589978e+14,5642503,M,2016-04-29,2016-04-29,56,JARDIM DA PENHA,0,0,0,0,0,0,0,0
2,4.262962e+12,5642549,F,2016-04-29,2016-04-29,62,MATA DA PRAIA,0,0,0,0,0,0,0,0
3,8.679512e+11,5642828,F,2016-04-29,2016-04-29,8,PONTAL DE CAMBURI,0,0,0,0,0,0,0,0
4,8.841186e+12,5642494,F,2016-04-29,2016-04-29,56,JARDIM DA PENHA,0,1,1,0,0,0,0,0